# syntax=docker/dockerfile:1

FROM docker.io/alpine:3.21 AS base

USER root

RUN apk add --no-cache sudo bash bash-completion git aws-cli curl ca-certificates jq \
    && rm -rf /var/cache/apk/* \
    && ln -s /var/cache/apk /etc/apk/cache

ENV TZ="Asia/Singapore" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8"
