# syntax=docker.io/docker/dockerfile:1

FROM docker.io/node:23.6.1-bookworm AS base

USER root

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends locales-all \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Asia/Singapore \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    PNPM_HOME=/opt/pnpm

ENV PATH="${PNPM_HOME}:${PATH}"

RUN npm install -g pnpm
