# syntax=docker/dockerfile:1

FROM docker.io/node:23.4.0-alpine AS base

ENV TZ="Asia/Singapore" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8" \
    PNPM_HOME="/opt/pnpm"

ENV PATH="${PNPM_HOME}:${PATH}"

RUN npm install -g pnpm typescript

USER root
